use_frameworks!

platform :ios, '10.0'

target 'WDQExtension_Example' do
  pod 'WDQExtension', :path => '../'

  target 'WDQExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
